# Crea fahrcel.exe


CFLAGS   = -std=c11 -Wall -pedantic-errors -m32 -D __DEBUG__ -g3 $(INCS)
# LDFLAGS  = -static-libgcc
INCS     = -I"C:/Program Files/Dev-Cpp/MinGW64/x86_64-w64-mingw32/
include"
LDLIBS   = -L"C:/Program Files/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32"


fahrcel.exe: fahrcel.o conversion.o
 gcc fahrcel.o conversion.o -o fahrcel.exe $(CFLAGS) $(LDFLAGS) $(LDLIBS) 


fahrcel.o: fahrcel.c conversion.h
 gcc -c fahrcel.c -o fahrcel.o $(CFLAGS)


conversion.o: conversion.h conversion.c
 gcc -c conversion.c -o conversion.o $(CFLAGS)


.PHONY: clean
clean:
 rm -f fahrcel.o conversion.o fahrcel.exe
